export const resList = [
	{
		info: {
			id: "16073",
			name: "California Burrito",
			cloudinaryImageId: "27238ee4292d42c7b705f2ce8671ff80",
			locality: "Malleshwaram",
			areaName: "Malleshwaram",
			costForTwo: "₹250 for two",
			cuisines: [
				"Mexican",
				"American",
				"Salads",
				"Continental",
				"Keto",
				"Healthy Food",
			],
			avgRating: 4.6,
			parentId: "1252",
			avgRatingString: "4.6",
			totalRatingsString: "10K+",
			sla: {
				deliveryTime: 39,
				lastMileTravel: 5,
				serviceability: "SERVICEABLE",
				slaString: "35-40 mins",
				lastMileTravelString: "5.0 km",
				iconType: "ICON_TYPE_EMPTY",
			},
			availability: {
				nextCloseTime: "2024-03-10 23:00:00",
				opened: true,
			},
			badges: {
				textExtendedBadges: [
					{
						iconId: "guiltfree/GF_Logo_android_3x",
						shortDescription: "options available",
						fontColor: "#7E808C",
					},
				],
			},
			isOpen: true,
			aggregatedDiscountInfoV2: {},
			type: "F",
			badgesV2: {
				entityBadges: {
					imageBased: {},
					textBased: {},
					textExtendedBadges: {
						badgeObject: [
							{
								attributes: {
									description: "",
									fontColor: "#7E808C",
									iconId: "guiltfree/GF_Logo_android_3x",
									shortDescription: "options available",
								},
							},
						],
					},
				},
			},
			orderabilityCommunication: {
				title: {},
				subTitle: {},
				message: {},
				customIcon: {},
			},
			differentiatedUi: {
				displayType: "ADS_UI_DISPLAY_TYPE_ENUM_DEFAULT",
				differentiatedUiMediaDetails: {
					mediaType: "ADS_MEDIA_ENUM_IMAGE",
					lottie: {},
					video: {},
				},
			},
			reviewsSummary: {},
			displayType: "RESTAURANT_DISPLAY_TYPE_DEFAULT",
			restaurantOfferPresentationInfo: {},
		},
		analytics: {
			context: "seo-data-23917786-7be5-4483-9ac2-7b931859f656",
		},
		cta: {
			link: "https://www.swiggy.com/restaurants/california-burrito-malleshwaram-bangalore-16073",
			text: "RESTAURANT_MENU",
			type: "WEBLINK",
		},
		widgetId: "collectionV5RestaurantListWidget_SimRestoRelevance_food_seo",
	},
	{
		info: {
			id: "502999",
			name: "BOX8 - Desi Meals",
			cloudinaryImageId: "69a061b7e0f951cef2b4947946f94ec6",
			locality: "Lakshmi Road",
			areaName: "Shanti Nagar",
			costForTwo: "₹250 for two",
			cuisines: ["North Indian", "Biryani", "Thalis", "Home Food"],
			avgRating: 4.5,
			parentId: "10655",
			avgRatingString: "4.5",
			totalRatingsString: "500+",
			sla: {
				deliveryTime: 21,
				lastMileTravel: 2.5,
				serviceability: "SERVICEABLE",
				slaString: "16-26 mins",
				lastMileTravelString: "2.5 km",
				iconType: "ICON_TYPE_EMPTY",
			},
			availability: {
				nextCloseTime: "2024-03-11 02:00:00",
				opened: true,
			},
			badges: {
				textExtendedBadges: [
					{
						iconId: "guiltfree/GF_Logo_android_3x",
						shortDescription: "options available",
						fontColor: "#7E808C",
					},
				],
			},
			isOpen: true,
			type: "F",
			badgesV2: {
				entityBadges: {
					imageBased: {},
					textBased: {},
					textExtendedBadges: {
						badgeObject: [
							{
								attributes: {
									description: "",
									fontColor: "#7E808C",
									iconId: "guiltfree/GF_Logo_android_3x",
									shortDescription: "options available",
								},
							},
						],
					},
				},
			},
			aggregatedDiscountInfoV3: {
				header: "50% OFF",
				subHeader: "UPTO ₹100",
			},
			orderabilityCommunication: {
				title: {},
				subTitle: {},
				message: {},
				customIcon: {},
			},
			differentiatedUi: {
				displayType: "ADS_UI_DISPLAY_TYPE_ENUM_DEFAULT",
				differentiatedUiMediaDetails: {
					mediaType: "ADS_MEDIA_ENUM_IMAGE",
					lottie: {},
					video: {},
				},
			},
			reviewsSummary: {},
			displayType: "RESTAURANT_DISPLAY_TYPE_DEFAULT",
			restaurantOfferPresentationInfo: {},
		},
		analytics: {
			context: "seo-data-23917786-7be5-4483-9ac2-7b931859f656",
		},
		cta: {
			link: "https://www.swiggy.com/restaurants/box8-desi-meals-lakshmi-road-shanti-nagar-bangalore-502999",
			text: "RESTAURANT_MENU",
			type: "WEBLINK",
		},
		widgetId: "collectionV5RestaurantListWidget_SimRestoRelevance_food_seo",
	},
	{
		info: {
			id: "393840",
			name: "Chinese Wok",
			cloudinaryImageId: "e0839ff574213e6f35b3899ebf1fc597",
			locality: "Chikka Lakshmaiah Layout",
			areaName: "Adugodi",
			costForTwo: "₹250 for two",
			cuisines: ["Chinese", "Asian", "Tibetan", "Desserts"],
			avgRating: 4.1,
			parentId: "61955",
			avgRatingString: "4.1",
			totalRatingsString: "1K+",
			sla: {
				deliveryTime: 49,
				lastMileTravel: 6.6,
				serviceability: "SERVICEABLE",
				slaString: "45-50 mins",
				lastMileTravelString: "6.6 km",
				iconType: "ICON_TYPE_EMPTY",
			},
			availability: {
				nextCloseTime: "2024-03-11 02:00:00",
				opened: true,
			},
			badges: {},
			isOpen: true,
			type: "F",
			badgesV2: {
				entityBadges: {
					imageBased: {},
					textBased: {},
					textExtendedBadges: {},
				},
			},
			aggregatedDiscountInfoV3: {
				header: "50% OFF",
				subHeader: "UPTO ₹100",
			},
			orderabilityCommunication: {
				title: {},
				subTitle: {},
				message: {},
				customIcon: {},
			},
			differentiatedUi: {
				displayType: "ADS_UI_DISPLAY_TYPE_ENUM_DEFAULT",
				differentiatedUiMediaDetails: {
					mediaType: "ADS_MEDIA_ENUM_IMAGE",
					lottie: {},
					video: {},
				},
			},
			reviewsSummary: {},
			displayType: "RESTAURANT_DISPLAY_TYPE_DEFAULT",
			restaurantOfferPresentationInfo: {},
		},
		analytics: {
			context: "seo-data-23917786-7be5-4483-9ac2-7b931859f656",
		},
		cta: {
			link: "https://www.swiggy.com/restaurants/chinese-wok-chikka-lakshmaiah-layout-adugodi-bangalore-393840",
			text: "RESTAURANT_MENU",
			type: "WEBLINK",
		},
		widgetId: "collectionV5RestaurantListWidget_SimRestoRelevance_food_seo",
	},
	{
		info: {
			id: "8766",
			name: "Beijing Bites",
			cloudinaryImageId: "ca0eb08d0635fd6da2e5a480fec897d0",
			locality: "Richmond Town",
			areaName: "Richmond Town",
			costForTwo: "₹450 for two",
			cuisines: ["Chinese"],
			avgRating: 4.3,
			parentId: "103",
			avgRatingString: "4.3",
			totalRatingsString: "10K+",
			sla: {
				deliveryTime: 26,
				lastMileTravel: 2.4,
				serviceability: "SERVICEABLE",
				slaString: "25-30 mins",
				lastMileTravelString: "2.4 km",
				iconType: "ICON_TYPE_EMPTY",
			},
			availability: {
				nextCloseTime: "2024-03-11 00:00:00",
				opened: true,
			},
			badges: {
				textExtendedBadges: [
					{
						iconId: "guiltfree/GF_Logo_android_3x",
						shortDescription: "options available",
						fontColor: "#7E808C",
					},
				],
			},
			isOpen: true,
			type: "F",
			badgesV2: {
				entityBadges: {
					imageBased: {},
					textBased: {},
					textExtendedBadges: {
						badgeObject: [
							{
								attributes: {
									description: "",
									fontColor: "#7E808C",
									iconId: "guiltfree/GF_Logo_android_3x",
									shortDescription: "options available",
								},
							},
						],
					},
				},
			},
			aggregatedDiscountInfoV3: {
				header: "50% OFF",
				subHeader: "UPTO ₹100",
			},
			orderabilityCommunication: {
				title: {},
				subTitle: {},
				message: {},
				customIcon: {},
			},
			differentiatedUi: {
				displayType: "ADS_UI_DISPLAY_TYPE_ENUM_DEFAULT",
				differentiatedUiMediaDetails: {
					mediaType: "ADS_MEDIA_ENUM_IMAGE",
					lottie: {},
					video: {},
				},
			},
			reviewsSummary: {},
			displayType: "RESTAURANT_DISPLAY_TYPE_DEFAULT",
			restaurantOfferPresentationInfo: {},
		},
		analytics: {
			context: "seo-data-23917786-7be5-4483-9ac2-7b931859f656",
		},
		cta: {
			link: "https://www.swiggy.com/restaurants/beijing-bites-richmond-town-bangalore-8766",
			text: "RESTAURANT_MENU",
			type: "WEBLINK",
		},
		widgetId: "collectionV5RestaurantListWidget_SimRestoRelevance_food_seo",
	},
	{
		info: {
			id: "736105",
			name: "Sorbetto - Ice Creams",
			cloudinaryImageId: "421458f15518deb6eb09a6f168daaf4b",
			locality: "Beside HYDERABAD BIRYANI HOUSE",
			areaName: "Koramangala",
			costForTwo: "₹300 for two",
			cuisines: ["Desserts", "Ice Cream", "Beverages"],
			avgRating: 4.4,
			veg: true,
			parentId: "488911",
			avgRatingString: "4.4",
			totalRatingsString: "100+",
			sla: {
				deliveryTime: 45,
				lastMileTravel: 7.4,
				serviceability: "SERVICEABLE",
				slaString: "40-45 mins",
				lastMileTravelString: "7.4 km",
				iconType: "ICON_TYPE_EMPTY",
			},
			availability: {
				nextCloseTime: "2024-03-11 07:00:00",
				opened: true,
			},
			badges: {},
			isOpen: true,
			type: "F",
			badgesV2: {
				entityBadges: {
					imageBased: {},
					textBased: {},
					textExtendedBadges: {},
				},
			},
			aggregatedDiscountInfoV3: {
				header: "15% OFF",
				subHeader: "ABOVE ₹700",
				discountTag: "FLAT DEAL",
			},
			orderabilityCommunication: {
				title: {},
				subTitle: {},
				message: {},
				customIcon: {},
			},
			differentiatedUi: {
				displayType: "ADS_UI_DISPLAY_TYPE_ENUM_DEFAULT",
				differentiatedUiMediaDetails: {
					mediaType: "ADS_MEDIA_ENUM_IMAGE",
					lottie: {},
					video: {},
				},
			},
			reviewsSummary: {},
			displayType: "RESTAURANT_DISPLAY_TYPE_DEFAULT",
			restaurantOfferPresentationInfo: {},
		},
		analytics: {
			context: "seo-data-23917786-7be5-4483-9ac2-7b931859f656",
		},
		cta: {
			link: "https://www.swiggy.com/restaurants/sorbetto-ice-creams-beside-hyderabad-biryani-house-koramangala-bangalore-736105",
			text: "RESTAURANT_MENU",
			type: "WEBLINK",
		},
		widgetId: "collectionV5RestaurantListWidget_SimRestoRelevance_food_seo",
	},
	{
		info: {
			id: "61790",
			name: "Sardarji Londonwaley",
			cloudinaryImageId: "lnkjhjadib8kmjogoopt",
			locality: "7th Block",
			areaName: "Koramangala",
			costForTwo: "₹350 for two",
			cuisines: ["Indian", "North Indian", "Punjabi", "Chinese", "Biryani"],
			avgRating: 4.1,
			parentId: "7808",
			avgRatingString: "4.1",
			totalRatingsString: "10K+",
			sla: {
				deliveryTime: 48,
				lastMileTravel: 6.2,
				serviceability: "SERVICEABLE",
				slaString: "45-50 mins",
				lastMileTravelString: "6.2 km",
				iconType: "ICON_TYPE_EMPTY",
			},
			availability: {
				nextCloseTime: "2024-03-10 23:59:00",
				opened: true,
			},
			badges: {},
			isOpen: true,
			type: "F",
			badgesV2: {
				entityBadges: {
					imageBased: {},
					textBased: {},
					textExtendedBadges: {},
				},
			},
			aggregatedDiscountInfoV3: {
				header: "15% OFF",
				subHeader: "ABOVE ₹900",
				discountTag: "FLAT DEAL",
			},
			orderabilityCommunication: {
				title: {},
				subTitle: {},
				message: {},
				customIcon: {},
			},
			differentiatedUi: {
				displayType: "ADS_UI_DISPLAY_TYPE_ENUM_DEFAULT",
				differentiatedUiMediaDetails: {
					mediaType: "ADS_MEDIA_ENUM_IMAGE",
					lottie: {},
					video: {},
				},
			},
			reviewsSummary: {},
			displayType: "RESTAURANT_DISPLAY_TYPE_DEFAULT",
			restaurantOfferPresentationInfo: {},
		},
		analytics: {
			context: "seo-data-23917786-7be5-4483-9ac2-7b931859f656",
		},
		cta: {
			link: "https://www.swiggy.com/restaurants/sardarji-londonwaley-7th-block-koramangala-bangalore-61790",
			text: "RESTAURANT_MENU",
			type: "WEBLINK",
		},
		widgetId: "collectionV5RestaurantListWidget_SimRestoRelevance_food_seo",
	},
	{
		info: {
			id: "712380",
			name: "Chicago Pizza",
			cloudinaryImageId: "80f040545552605e33eba09f8fa30be9",
			locality: "khb colony",
			areaName: "Koramangala",
			costForTwo: "₹500 for two",
			cuisines: ["Pizzas", "Fast Food", "Italian"],
			avgRating: 4.1,
			parentId: "60277",
			avgRatingString: "4.1",
			totalRatingsString: "100+",
			sla: {
				deliveryTime: 49,
				lastMileTravel: 6.7,
				serviceability: "SERVICEABLE",
				slaString: "45-50 mins",
				lastMileTravelString: "6.7 km",
				iconType: "ICON_TYPE_EMPTY",
			},
			availability: {
				nextCloseTime: "2024-03-11 01:15:00",
				opened: true,
			},
			badges: {},
			isOpen: true,
			type: "F",
			badgesV2: {
				entityBadges: {
					imageBased: {},
					textBased: {},
					textExtendedBadges: {},
				},
			},
			aggregatedDiscountInfoV3: {
				header: "₹125 OFF",
				subHeader: "ABOVE ₹499",
				discountTag: "FLAT DEAL",
			},
			orderabilityCommunication: {
				title: {},
				subTitle: {},
				message: {},
				customIcon: {},
			},
			differentiatedUi: {
				displayType: "ADS_UI_DISPLAY_TYPE_ENUM_DEFAULT",
				differentiatedUiMediaDetails: {
					mediaType: "ADS_MEDIA_ENUM_IMAGE",
					lottie: {},
					video: {},
				},
			},
			reviewsSummary: {},
			displayType: "RESTAURANT_DISPLAY_TYPE_DEFAULT",
			restaurantOfferPresentationInfo: {},
		},
		analytics: {
			context: "seo-data-23917786-7be5-4483-9ac2-7b931859f656",
		},
		cta: {
			link: "https://www.swiggy.com/restaurants/chicago-pizza-khb-colony-koramangala-bangalore-712380",
			text: "RESTAURANT_MENU",
			type: "WEBLINK",
		},
		widgetId: "collectionV5RestaurantListWidget_SimRestoRelevance_food_seo",
	},
	{
		info: {
			id: "3241",
			name: "Meghana Foods",
			cloudinaryImageId: "e0vvulfbahjxjz6k4uwi",
			locality: "Residency Road",
			areaName: "Residency Road",
			costForTwo: "₹500 for two",
			cuisines: ["Biryani", "Andhra", "South Indian", "Chinese", "Seafood"],
			avgRating: 4.6,
			parentId: "635",
			avgRatingString: "4.6",
			totalRatingsString: "10K+",
			sla: {
				deliveryTime: 25,
				lastMileTravel: 2.1,
				serviceability: "SERVICEABLE",
				slaString: "25-30 mins",
				lastMileTravelString: "2.1 km",
				iconType: "ICON_TYPE_EMPTY",
			},
			availability: {
				nextCloseTime: "2024-03-11 01:30:00",
				opened: true,
			},
			badges: {},
			isOpen: true,
			type: "F",
			badgesV2: {
				entityBadges: {
					imageBased: {},
					textBased: {},
					textExtendedBadges: {},
				},
			},
			aggregatedDiscountInfoV3: {
				header: "FREE ITEM",
			},
			orderabilityCommunication: {
				title: {},
				subTitle: {},
				message: {},
				customIcon: {},
			},
			differentiatedUi: {
				displayType: "ADS_UI_DISPLAY_TYPE_ENUM_DEFAULT",
				differentiatedUiMediaDetails: {
					mediaType: "ADS_MEDIA_ENUM_IMAGE",
					lottie: {},
					video: {},
				},
			},
			reviewsSummary: {},
			displayType: "RESTAURANT_DISPLAY_TYPE_DEFAULT",
			restaurantOfferPresentationInfo: {},
		},
		analytics: {
			context: "seo-data-23917786-7be5-4483-9ac2-7b931859f656",
		},
		cta: {
			link: "https://www.swiggy.com/restaurants/meghana-foods-residency-road-bangalore-3241",
			text: "RESTAURANT_MENU",
			type: "WEBLINK",
		},
		widgetId: "collectionV5RestaurantListWidget_SimRestoRelevance_food_seo",
	},
	{
		info: {
			id: "464509",
			name: "Leon's - Burgers & Wings (Leon Grill)",
			cloudinaryImageId: "b2edbc28b7b8219d6e0a9c049ce06658",
			locality: "Frazer Town",
			areaName: "Frazer Town",
			costForTwo: "₹300 for two",
			cuisines: ["American", "Snacks", "Turkish", "Portuguese", "Continental"],
			avgRating: 4.5,
			parentId: "371281",
			avgRatingString: "4.5",
			totalRatingsString: "5K+",
			sla: {
				deliveryTime: 28,
				lastMileTravel: 4.2,
				serviceability: "SERVICEABLE",
				slaString: "25-30 mins",
				lastMileTravelString: "4.2 km",
				iconType: "ICON_TYPE_EMPTY",
			},
			availability: {
				nextCloseTime: "2024-03-11 03:00:00",
				opened: true,
			},
			badges: {},
			isOpen: true,
			type: "F",
			badgesV2: {
				entityBadges: {
					imageBased: {},
					textBased: {},
					textExtendedBadges: {},
				},
			},
			aggregatedDiscountInfoV3: {
				header: "₹125 OFF",
				subHeader: "ABOVE ₹249",
				discountTag: "FLAT DEAL",
			},
			orderabilityCommunication: {
				title: {},
				subTitle: {},
				message: {},
				customIcon: {},
			},
			differentiatedUi: {
				displayType: "ADS_UI_DISPLAY_TYPE_ENUM_DEFAULT",
				differentiatedUiMediaDetails: {
					mediaType: "ADS_MEDIA_ENUM_IMAGE",
					lottie: {},
					video: {},
				},
			},
			reviewsSummary: {},
			displayType: "RESTAURANT_DISPLAY_TYPE_DEFAULT",
			restaurantOfferPresentationInfo: {},
		},
		analytics: {
			context: "seo-data-23917786-7be5-4483-9ac2-7b931859f656",
		},
		cta: {
			link: "https://www.swiggy.com/restaurants/leons-burgers-and-wings-leon-grill-frazer-town-bangalore-464509",
			text: "RESTAURANT_MENU",
			type: "WEBLINK",
		},
		widgetId: "collectionV5RestaurantListWidget_SimRestoRelevance_food_seo",
	},
];
